//
// Created by fowle on 9/29/2023.
//

#ifndef PROJECT_6_COUNTING_CUBE_ARRANGEMENTS_MAIN_H
#define PROJECT_6_COUNTING_CUBE_ARRANGEMENTS_MAIN_H


class main {

};


#endif //PROJECT_6_COUNTING_CUBE_ARRANGEMENTS_MAIN_H
